//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Этот исходный текст был создан автоматически: Microsoft.VSDesigner, версия: 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace WCFWebClient.localhost {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="BasicHttpBinding_IService", Namespace="http://tempuri.org/")]
    public partial class Service : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetListEmpOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetListDepOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetItemEmpOperationCompleted;
        
        private System.Threading.SendOrPostCallback CreateEmpOperationCompleted;
        
        private System.Threading.SendOrPostCallback DeleteEmpOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdateEmpOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Service() {
            this.Url = global::WCFWebClient.Properties.Settings.Default.WCFWebClient_localhost_Service;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetListEmpCompletedEventHandler GetListEmpCompleted;
        
        /// <remarks/>
        public event GetListDepCompletedEventHandler GetListDepCompleted;
        
        /// <remarks/>
        public event GetItemEmpCompletedEventHandler GetItemEmpCompleted;
        
        /// <remarks/>
        public event CreateEmpCompletedEventHandler CreateEmpCompleted;
        
        /// <remarks/>
        public event DeleteEmpCompletedEventHandler DeleteEmpCompleted;
        
        /// <remarks/>
        public event UpdateEmpCompletedEventHandler UpdateEmpCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService/GetListEmp", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/WCFWebService.Model")]
        public Employee[] GetListEmp() {
            object[] results = this.Invoke("GetListEmp", new object[0]);
            return ((Employee[])(results[0]));
        }
        
        /// <remarks/>
        public void GetListEmpAsync() {
            this.GetListEmpAsync(null);
        }
        
        /// <remarks/>
        public void GetListEmpAsync(object userState) {
            if ((this.GetListEmpOperationCompleted == null)) {
                this.GetListEmpOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetListEmpOperationCompleted);
            }
            this.InvokeAsync("GetListEmp", new object[0], this.GetListEmpOperationCompleted, userState);
        }
        
        private void OnGetListEmpOperationCompleted(object arg) {
            if ((this.GetListEmpCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetListEmpCompleted(this, new GetListEmpCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService/GetListDep", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/WCFWebService.Model")]
        public Department[] GetListDep() {
            object[] results = this.Invoke("GetListDep", new object[0]);
            return ((Department[])(results[0]));
        }
        
        /// <remarks/>
        public void GetListDepAsync() {
            this.GetListDepAsync(null);
        }
        
        /// <remarks/>
        public void GetListDepAsync(object userState) {
            if ((this.GetListDepOperationCompleted == null)) {
                this.GetListDepOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetListDepOperationCompleted);
            }
            this.InvokeAsync("GetListDep", new object[0], this.GetListDepOperationCompleted, userState);
        }
        
        private void OnGetListDepOperationCompleted(object arg) {
            if ((this.GetListDepCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetListDepCompleted(this, new GetListDepCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService/GetItemEmp", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public Employee GetItemEmp(int id, [System.Xml.Serialization.XmlIgnoreAttribute()] bool idSpecified) {
            object[] results = this.Invoke("GetItemEmp", new object[] {
                        id,
                        idSpecified});
            return ((Employee)(results[0]));
        }
        
        /// <remarks/>
        public void GetItemEmpAsync(int id, bool idSpecified) {
            this.GetItemEmpAsync(id, idSpecified, null);
        }
        
        /// <remarks/>
        public void GetItemEmpAsync(int id, bool idSpecified, object userState) {
            if ((this.GetItemEmpOperationCompleted == null)) {
                this.GetItemEmpOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetItemEmpOperationCompleted);
            }
            this.InvokeAsync("GetItemEmp", new object[] {
                        id,
                        idSpecified}, this.GetItemEmpOperationCompleted, userState);
        }
        
        private void OnGetItemEmpOperationCompleted(object arg) {
            if ((this.GetItemEmpCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetItemEmpCompleted(this, new GetItemEmpCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService/CreateEmp", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void CreateEmp([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] Employee item) {
            this.Invoke("CreateEmp", new object[] {
                        item});
        }
        
        /// <remarks/>
        public void CreateEmpAsync(Employee item) {
            this.CreateEmpAsync(item, null);
        }
        
        /// <remarks/>
        public void CreateEmpAsync(Employee item, object userState) {
            if ((this.CreateEmpOperationCompleted == null)) {
                this.CreateEmpOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCreateEmpOperationCompleted);
            }
            this.InvokeAsync("CreateEmp", new object[] {
                        item}, this.CreateEmpOperationCompleted, userState);
        }
        
        private void OnCreateEmpOperationCompleted(object arg) {
            if ((this.CreateEmpCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CreateEmpCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService/DeleteEmp", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void DeleteEmp(int id, [System.Xml.Serialization.XmlIgnoreAttribute()] bool idSpecified) {
            this.Invoke("DeleteEmp", new object[] {
                        id,
                        idSpecified});
        }
        
        /// <remarks/>
        public void DeleteEmpAsync(int id, bool idSpecified) {
            this.DeleteEmpAsync(id, idSpecified, null);
        }
        
        /// <remarks/>
        public void DeleteEmpAsync(int id, bool idSpecified, object userState) {
            if ((this.DeleteEmpOperationCompleted == null)) {
                this.DeleteEmpOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDeleteEmpOperationCompleted);
            }
            this.InvokeAsync("DeleteEmp", new object[] {
                        id,
                        idSpecified}, this.DeleteEmpOperationCompleted, userState);
        }
        
        private void OnDeleteEmpOperationCompleted(object arg) {
            if ((this.DeleteEmpCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DeleteEmpCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService/UpdateEmp", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void UpdateEmp([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] Employee item) {
            this.Invoke("UpdateEmp", new object[] {
                        item});
        }
        
        /// <remarks/>
        public void UpdateEmpAsync(Employee item) {
            this.UpdateEmpAsync(item, null);
        }
        
        /// <remarks/>
        public void UpdateEmpAsync(Employee item, object userState) {
            if ((this.UpdateEmpOperationCompleted == null)) {
                this.UpdateEmpOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateEmpOperationCompleted);
            }
            this.InvokeAsync("UpdateEmp", new object[] {
                        item}, this.UpdateEmpOperationCompleted, userState);
        }
        
        private void OnUpdateEmpOperationCompleted(object arg) {
            if ((this.UpdateEmpCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateEmpCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/WCFWebService.Model")]
    public partial class Employee {
        
        private int ageField;
        
        private bool ageFieldSpecified;
        
        private System.Nullable<int> departmentIdField;
        
        private bool departmentIdFieldSpecified;
        
        private int idField;
        
        private bool idFieldSpecified;
        
        private string nameField;
        
        private double salaryField;
        
        private bool salaryFieldSpecified;
        
        /// <remarks/>
        public int Age {
            get {
                return this.ageField;
            }
            set {
                this.ageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AgeSpecified {
            get {
                return this.ageFieldSpecified;
            }
            set {
                this.ageFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> DepartmentId {
            get {
                return this.departmentIdField;
            }
            set {
                this.departmentIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DepartmentIdSpecified {
            get {
                return this.departmentIdFieldSpecified;
            }
            set {
                this.departmentIdFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IdSpecified {
            get {
                return this.idFieldSpecified;
            }
            set {
                this.idFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public double Salary {
            get {
                return this.salaryField;
            }
            set {
                this.salaryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SalarySpecified {
            get {
                return this.salaryFieldSpecified;
            }
            set {
                this.salaryFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/WCFWebService.Model")]
    public partial class Department {
        
        private int idField;
        
        private bool idFieldSpecified;
        
        private string nameField;
        
        /// <remarks/>
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IdSpecified {
            get {
                return this.idFieldSpecified;
            }
            set {
                this.idFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void GetListEmpCompletedEventHandler(object sender, GetListEmpCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetListEmpCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetListEmpCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Employee[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Employee[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void GetListDepCompletedEventHandler(object sender, GetListDepCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetListDepCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetListDepCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Department[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Department[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void GetItemEmpCompletedEventHandler(object sender, GetItemEmpCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetItemEmpCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetItemEmpCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Employee Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Employee)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void CreateEmpCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void DeleteEmpCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void UpdateEmpCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
}

#pragma warning restore 1591